# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: ^(sample_project)/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args:
          - "--settings-path=pyproject.toml"

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args:
          - "--config=pyproject.toml"
          # language_version: python3.8

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - "--config=.flake8"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.5.1" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args:
          - "--config=pyproject.toml"
        additional_dependencies:
          - "fastapi-sqlalchemy"
          - "fastapi"
          - "pydantic"
          - "strawberry-graphql"
          - "rich-strawberry"
          - "pydantic-settings"
